export const storyList12 = [
  'I am Roy. I am a big boy. </br> I can play bat and ball. </br> Pam is a little girl. </br>She can play bat and ball.',
  'I have two brown and white cats. They love to run and play. They love milk. Father has a pet at home too. He has a pet dog and it loves to run and jump. The dog is black with white. It loves to eat food. It is big. When I go to school, my mother stays at home with our pets.',
  'The Farm Pat lives on a farm. There are pigs and hens on the farm. It rains on the farm. The hens run to get out of the rain. They look funny when they are wet. The pigs like to play in the rain. The rain is good for the farmer. He can get good things to take to the market. After the rain stops, the farmer goes to the market. He likes to go to the market.',
  'Cake day at home My name is Peter. There are four of us at home, mother, father, Ann and I. We have cake day at home. Mother and Ann make the cake. First, they buy the things they need. Then they read the labels, wash their hands, and write what they should do. Mother and Ann sing when they bake. Father and I work in the yard. When the cake is done, mother takes it from the oven. She puts it to cool on the table. We wash up and then we eat our cake. We love our cake day at home.',
  'Tom and his friends love to draw and paint. Together they do pretty pictures in class. They do their best work when they are at school. First, they think about what they would want to draw. Then they get all the items that they need. Next, they begin. Tom likes to use cold colours when he draws and paints. Cold colours are blue, green and purple. His friends like to use warm colours like red, yellow, and orange. When they work together, they use only the three Primary colours to get all the six colours. The Primary colours are red, yellow, and blue. If the paint falls on the floor, they clean it up. When they are finished painting, they show their work to their friends and family. Friends and family will buy their paintings.',
  'Sports days at school are an important part of our culture. Athletes and non-athletes look forward to this activity-filled event. This annual event is normally held on the two days before Ash Wednesday. The excitement begins weeks, even months before the big days. Students and teachers dress in their house colours, sing cheers, and practice for each event. Some of the events include cheerleading, cross-country races, the one hundred and eight hundred meter races, shuttle relays, and my favorite, the baton relay. Glucose, oranges, and water are a must-have for these days as the days are usually very hot and runners get very competitive. Coaches and teachers select their best runners or the person they believe would have a chance at winning. There are four houses at our school: Red House, Blue House, Yellow House, and Green House. I had recently transferred from another school, and my house leader or captain did not know about my abilities. On the day of the big events, I pleaded with the house leader to let me run, but I was told they already had all the athletes for each race. So, I went back to my seat to continue watching the races. When it was time for the eight hundred meter race, the announcer called for two runners from each house. I overheard the house leader and captain discussing that they only had one name written down. I immediately volunteered myself. Both looked at me from head to toe, as if to say, "He is so frail." The announcer repeated the call, and they said, "Go ahead." I quickly changed into my gear and confidently walked onto the field to the starting position. That day, I surpassed everyone’s expectations.',
  'My name is Abby, and my dream is to become a renowned Scientist. A scientist is someone who conducts scientific research to advance knowledge in an area of interest. Scientists are great, and they help people. That is why Science is my favourite subject. My area of interest and the most important thing to me in Science class is the studying of insects. During that period, I am very attentive, especially when practical work is involved. Insects are different and very interesting creatures, so I want to learn everything about them. When it is time to explore, I set up an area and then I begin my work. I look for all kinds of insects and put them in different categories. These categories include ants, bugs, and worms. Whenever I collect different species, I compare them to each other to see what new information I can learn. You would be amazed at the number of different species of worms and bugs inhabiting an area. Furthermore, you would be even more fascinated by the valuable contributions that they make to the environment. I worry about some of these insects becoming extinct. As a result, I want to have a thorough understanding of their needs, challenges, and life cycle of each and every insect in my surroundings.',
  "Viruses can make you sick. That's why you should practice proper hygiene. Wash your hands after using the bathroom and before you eat. They can become an epidemic with many people being infected. This is because of globalization, travel, and trade. Things can get worse, and the virus later becomes a pandemic if we are not very careful. This can cause many vulnerable people to become sick or later die. These viruses can cause many people to develop flu symptoms, including a cough or a cold, that later causes pneumonia, resulting in severe respiratory problems. In 2020, we had the pandemic of the Novel Coronavirus. It crossed many country borders, caused many illnesses, and had a devastating effect on their economy. Since people were asked to stay inside to contain the spread, many industries had to close. Tourism, travel, and entertainment were the worst hit. Schools also had to close, and many businesses had to change their model to online operations. Some businesses were ready, and others werent; consequently, those did not survive. Governments all over the world had to provide stimulus packages to boost their economy to ensure that they did not collapse or go into a deep recession. Mental health became an issue as people struggled to cope with the situation.",
];

const story1 = [
  'I am Roy.',
  'I am a big boy.',
  'I can play bat and ball.',
  'Pam is a little girl.',
  'She can play bat and ball.',
];
const story2 = [
  'I have two brown and white cats.',
  'They love to run and play.',
  'They love milk.',
  'Father has a pet at home too.',
  'He has a pet dog and it loves to run and jump.',
  'The dog is black with white.',
  'It loves to eat food. It is big.',
  'When I go to school,',
  'my mother stays at home with our pets.',
];
const story3 = [
  'The Farm',
  'Pat lives on a farm.',
  'There are pigs and hens on the farm.',
  'It rains on the farm.',
  'The hens run to get out of the rain.',
  'They look funny when they are wet.',
  'The pigs like to play in the rain.',
  'The rain is good for the farmer.',
  'He can get good things to take to the market.',
  'After the rain stops, the farmer goes to the market.',
  'He likes to go to the market.',
];

const story4 = [
  'Cake day at home',
  'My name is Peter. There are four of us at home: mother, father, Ann, and I.',
  'We have cake day at home.',
  'Mother and Ann make the cake.',
  'First, they buy the things they need..',
  'Then they read the labels, wash their hands, and write what they should do.',
  'Mother and Ann sing when they bake. Father and I work in the yard.',
  'When the cake is done, mother takes it from the oven.',
  'She puts it to cool on the table.',
  'We wash up and then we eat our cake.',
  'We love our cake day at home.',
];
const story5 = [
  'Tom and his friends love to draw and paint.',
  'Together they do pretty pictures in class.',
  'They do their best work when they are at school.',
  'First, they think about what they would want to draw.',
  'Then they get all the items that they need. Next, they begin.',
  'Tom likes to use cold colours when he draws and paints.',
  'Cold colours are blue, green, and purple.',
  'His friends like to use warm colours like red, yellow, and orange.',
  'When they work together, they use only the three Primary colours to get all the six colours.',
  'The Primary colours are red, yellow, and blue.',
  'If the paint falls on the floor, they clean it up.',
  'When they are finished painting, they show their work to their friends and family.',
  'Friends and family will buy their paintings.',
];
const story6 = [
  'Sports Days',
  'Sports days at school are an important part of our culture.',
  'Athletes and non-athletes look forward to this activity-filled event.',
  'This annual event is normally held on the two days before Ash Wednesday.',
  'The excitement begins weeks, even months before the big days.',
  'Students and teachers dress in their house colours, sing cheers, and practice for each event.',
  'Some of the events include cheerleading, cross-country races, the one hundred up eight hundred meter races, shuttle relays, and my favorite, the baton relay.',
  'Glucose, oranges, and water are a must-have for these days as the days are usually very hot and runners get very competitive.',
  'Coaches and teachers select their best runners or the person they believe would have a chance at winning.',
  'There are four houses at our school: Red House, Blue House, Yellow House, and Green House.',
  'I had recently transferred from another school, and my house leader or captain did not know about my abilities.',
  'On the day of the big events, I pleaded with the house leader to let me run, I was told that they had all the athletes for each race already. ',
  'So, I went back to my seat to continue watching the races.',
  'When it was time for the eight hundred meter race, the announcer called for two runners from each house.',
  'I overheard the house leader and captain discussing that they only had one name written down.',
  'I immediately volunteered myself. Both looked at me from head to toe, as if to say, he is so frail.',
  'The announcer repeated the call, and they said go ahead.',
  'I quickly changed into my gear and confidently walked onto the field to the starting position.',
  ' That day, I surpassed everyone’s expectations.',
];
const story7 = [
  'My name is Abby, and my dream is to become a renowned Scientist.',
  'A scientist is someone who conducts scientific research to advance knowledge in an area of interest.',
  'Scientists are great, and they help people.',
  'That is why Science is my favourite subject.',
  'My area of interest and the most important thing to me in Science class is the studying of insects.',
  'During that period, I am very attentive, especially when practical work is involved.',
  'Insects are different and very interesting creatures, so I want to learn everything about them.',
  'When it is time to explore, I set up an area and then I begin my work.',
  'I look for all kinds of insects and put them in different categories.',
  'These categories include ants, bugs, and worms.',
  'Whenever I collect different species, I compare them to each other to see what new information I can learn.',
  'You would be amazed at the number of different species of worms and bugs inhabiting an area.',
  'Furthermore, you would be even more fascinated by the valuable contributions that they make to the environment.',
  'I worry about some of these insects becoming extinct.',
  'As a result, I want to have a thorough understanding of their needs, challenges, and life cycle of each and every insect in my surroundings.',
];
const story8 = [
  'Viruses can make you sick.',
  'That’s why you should practice proper hygiene.',
  'Wash your hands after using the bathroom and before you eat.',
  'They can become an epidemic with many people being infected.',
  'This is because of globalization, travel, and trade.',
  'Things can get worse, and the virus later becomes a pandemic if we are not very careful.',
  'This can cause many vulnerable people to become sick or later die.',
  'These viruses can cause many people to develop flu symptoms, including a cough or a cold, that later causes pneumonia, resulting in severe respiratory problems.',
  'In 2020, we had the pandemic of the Novel Coronavirus.',
  'It crossed many country borders, caused many illnesses, and had a devastating effect on their economy.',
  'Since people were asked to stay inside to contain the spread, many industries had to close.',
  'Tourism, travel, and entertainment were the worst hit.',
  'Schools also had to close, and many businesses had to change their model to online operations.',
  'Some businesses were ready, and others weren’t; consequently, those did not survive.',
  'Governments all over the world had to provide stimulus packages to boost their economy to ensure that they did not collapse or go into a deep recession.',
  'Mental health became an issue as people struggled to cope with the situation.',
];

export const storyList = [
  { story: story1 },
  { story: story2 },
  { story: story3 },
  { story: story4 },
  { story: story5 },
  { story: story6 },
  { story: story7 },
  { story: story8 },
];
